### ISSUE TITLE
How to handle errors

### ISSUE THREAD

**Issue by jensfinnas** [calebmer/postgrest-client#4]
How do I pick up errors from the Postgrest server?

Trying my way around with this pattern:
```javascript
api.get("/endpoint").end(function(err, data) {
  console.log(err, data)
})
````
And this one:
``` javascript
api.get("/endpoint").on('error', function(err) {
   console.log(err)
})
````

But not logging anything when I supposed to get errors.

**Comment by calebmer** [comment]
Look at the [`superagent`](http://visionmedia.github.io/superagent/) documentation. You should be able to find the answer there :+1:
